 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$pageTitle = $tr->translate("CREATE_INCEXP_CATEGORY");
	
	$this->headTitle($pageTitle);
	echo $this->headTitle();
	
	$frm = $this->frm;
	
?>
	<div class="container fb">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
					<h5 class="title"><?php echo $pageTitle;?></h5>
				</div>
				<div class="card-body">
					<div class="basic-form">
						<form id="form-submit" action="<?php echo $this->url(array('module'=>'section','controller'=>'expensecategory','action'=>'add')); ?>" method="POST" >
							<div class="mb-3 form-input">
								<span class="input-icon">
									<i class="fa-solid fa-layer-group"></i>
								</span>
								<?php echo $frm->getElement('title');?>
							</div>
							<div class="mb-3 form-input">
								<span class="input-icon">
									<i class="fa-solid fa-money-bill"></i>
								</span>
								<?php echo $frm->getElement('categoryType');?>
							</div>
							<button type="submit" class="btn btn-primary mt-3 btn-rounded btn-block"><?php echo $tr->translate('SAVE');?></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

<script>
$( document ).ready(function() {
    $('.classHeadTitle').html("<?php echo $pageTitle;?>");
	
	$("#form-submit").submit(function() {
		const categoryType = document.getElementById('categoryType').value;
		if(categoryType==''){
			alert("Select Type!");
			return false;
		}
	  return true;
	});
});
</script>