 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	
	
	$pageTitle = $tr->translate("INCEXP_CATEGORY");
	
	$this->headTitle($pageTitle);
	echo $this->headTitle();
	
	//print_r($this->rs);
	$frm = $this->frm;
	$urlEdit = $this->baseUrl()."/section/expensecategory/edit/id/";
	$addUrl = $this->baseUrl()."/section/expensecategory/add";
	
	$statusClose = '<span class="badge badge-circle badge-danger "><i class="fa fa-xmark"></i></span>';
	$statusCheck = '<span class="badge badge-circle badge-success"><i class="fa fa-check"></i></span>';
?>
	<div class="page-content">
		<div class="container"> 
			<div class="serach-area"> 
				<form id="form-submit" action="<?php echo $this->url(array('module'=>'section','controller'=>'expensecategory','action'=>'index')); ?>" method="POST" >
					<div class="input-group search-input">
						<?php echo $frm->getElement('search');?>
					</div>
					<div class="filter-area">
						<div>
							<h5><?php echo $pageTitle; ?></h5>
							<span><?php echo count($this->rs); ?><?php echo $tr->translate("CATEGORY"); ?></span>
						</div>
						<button type="submit" class="btn  filter-btn bg-skyblue light"><i class="fa-solid fa-magnifying-glass"></i></button>
					</div>
				</form>
				<?php if(!empty($this->rs)){?>
				<div class="dz-list data-list">
					<ul>
						<?php $i=0; 
						foreach($this->rs AS $rs){ $i++;
							$status=$statusClose;
							if($rs["status"]==1){
								$status=$statusCheck;
							}
							$categoryType = $tr->translate("INCOME");
							if($rs['categoryType']==1) {
								$categoryType = $tr->translate("EXPENSE");
							}
						
						?>
						<li>
							<div  class="item-content item-link">
								<div class="dz-icon bg-primary light">
									<?php echo $i;?>                                  
								</div>
								<div class="dz-inner d-flex align-items-center w-100">
									<div class="dz-title flex-1">
										<span class="dz-title"><?php echo $rs["title"];?></span>
										<span class="text-muted d-block fw-normal"><?php echo $categoryType;?></span>
									</div>
									<?php echo $status;?>
									<a class="btn light btn-warning fs-6 p-2 ms-2 fw-normal" href="<?php echo $urlEdit.$rs["id"]; ?>" >
									<i class="fa fa-edit"></i>
									</a>
								</div>
							</div>
						</li>
						<?php } ?>
					</ul>
					<?php } ?>                
				</div>    
		</div>
	</div>

<script>
$( document ).ready(function() {
    $('.classHeadTitle').html("<?php echo $pageTitle;?>");
});
</script>