 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$pageTitle = $tr->translate("ផលិតផល");
	$this->headTitle($pageTitle);
	echo $this->headTitle();
	$dbp= new Section_Model_DbTable_DbProduction;
	
	$formSearch = $this->formSearch;
	$urlEdit = $this->baseUrl()."/section/production/edit/id/";
	
	$statusClose = '<span class="badge badge-circle badge-danger "><i class="fa fa-xmark"></i></span>';
	$statusCheck = '<span class="badge badge-circle badge-success"><i class="fa fa-check"></i></span>';
?>
	<div class="page-content">
		<div class="container"> 
			<div class="serach-area"> 
				<div class="filter-area m-0">
					<div>
						<h5><?php echo $pageTitle;?></h5>
					</div>
					<a href="javascript:void(0);" class="filter-btn bg-skyblue light" data-bs-toggle="modal" data-bs-target="#basicModal">
						<i class="text-primary fa fa-filter "></i>
					</a>
				</div>
				<div class="list item-list recent-jobs-list">
					<ul>
						<?php
						 if(!empty($this->rs)) { foreach($this->rs as $row) { 
								$date = new DateTime($row["productionDate"]);
								$forDateMonth =  $date->format("M");
								$forDateYear =  $date->format("Y");
								$forDateDay =  $date->format("d");
								$status=$statusClose;
								if($row["isVoid"]==0){
									$status=$statusCheck;
								}
							?>
							<li>
								<div class="item-content align-items-center justify-content-between pt-2">
								</div>
								<div class="item-content align-items-center justify-content-between mb-2">
									<div class="media-55 rounded-2 bg-primary d-flex justify-content-center align-items-center flex-column" >
										<small class="item-title text-white lh-sm"><?php echo $forDateDay;?></small>
										<small class="item-title text-white lh-sm"><?php echo $forDateMonth;?></small>
										<small class="item-title text-white lh-sm" ><?php echo $forDateYear;?></small>
									</div>
									<div class="row m-0" style="width:100%;">
										<div class="col-8">
											<div class="d-flex align-items-center mb-0">
												អ្នករាប់់ :
												<div class="item-price text-red ms-2"><?php echo $row["counter"];?></div>
											</div>
											<div class="d-flex align-items-center mb-0">
												ចំណាំ :
												<div class="item-price text-red ms-2"><?php echo $row["note"];?></div>
											</div>
										</div>
										<div class="col-4 d-flex justify-content-around  align-items-center align-content-center  flex-row">
											<div ><?php echo $status;?></div>
											<div >
												<div class="basic-dropdown">
													<div class="dropdown">
														<button type="button" class="btn btn-body dropdown-toggle" data-bs-toggle="dropdown">
														<i class="fa fa-ellipsis-v me-2"></i>
														</button>
														<div class="dropdown-menu">
															<a class="dropdown-item" onclick="VoidForm('<?php echo $row['id']; ?>');" href="javascript:void(0);"><i class="text-primary fa fa-xmark me-2"></i> <?php echo $tr->translate("ទុកជាមោឃៈ");?></a>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="sortable-handler">
									<style>
										.table > :not(caption) > * > * {
											padding: 0.3rem 0.3rem;
											background-color: var(--bs-table-bg);
											border-bottom-width: 0px;
											box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg);
											font-size: 12px;
										}
									</style>
									<table id="materialTable" class="table table-striped">
										<thead>
											<tr class="table-info">
												<th class="text-center" colspan="3">ទំនិញ</th>
											</tr>
											<tr class="table-active ">
												<th class="text-center" width="10%">ល.រ</th>
												<th>ឈ្មោះ</th>
												<th class="text-center" width="30%">ចំនួន</th>
											</tr>
										</thead>
										<tbody>
											<?php
												$rsDetail = $dbp->getProductdetailById($row['id']);
												$i=0;
												if(!empty($rsDetail))foreach ($rsDetail AS $rs) {
												$i++;
											?>
												<tr >
													<td class="text-center"><?php echo $i; ?></td>
													<td ><?php echo $rs['productName'];?></td>
													<td class="text-center"><?php echo $rs['quantity'];?></td>
												</tr>
											<?php } ?>	 
										</tbody>
									</table>
								</div>
							</li>
							
						<?php }}?>
				   </ul>
				</div>   

			</div>    
		</div>
	</div>

	<div class="modal modal-bottom fade" id="basicModal"  aria-modal="true" role="dialog">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title"><?php echo $tr->translate("SEARCH");?></h5>
					<button class="btn-close" data-bs-dismiss="modal">
						<i class="fa-solid fa-xmark"></i>
					</button>
				</div>
				<form id="form-search" method="GET">
					<div class="modal-body">
						<div class="basic-form">
							<div class="mb-1 form-input">
								<span class="input-icon">
								   <i class="fa fa-search"></i>
								</span>
								<?php echo $formSearch->getElement('advSearch');?>
							</div>
							<div class="mb-1 form-input">
								<span class="input-icon">
								   <i class="fa fa-search"></i>
								</span>
								<?php echo $formSearch->getElement('startDate');?>
							</div>
							<div class="mb-1 form-input">
								<span class="input-icon">
								   <i class="fa fa-search"></i>
								</span>
								<?php echo $formSearch->getElement('endDate');?>
							</div>
							<div class="mb-1 form-input">
								<span class="input-icon">
								   <i class="fa fa-list-check"></i>
								</span>
								<?php echo $formSearch->getElement('isVoid');?>
							</div>	
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-sm btn-danger light" data-bs-dismiss="modal"><?php echo $tr->translate("CLOSE");?></button>
						<button type="submit" class="btn btn-sm btn-primary" data-bs-dismiss="modal" name="btn-search" ><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</form>
			</div>
		</div>
	</div>
<script>

$( document ).ready(function() {
    $('.classHeadTitle').html("<?php echo $pageTitle;?>");
});

function VoidForm(index) {
	url='<?php echo $this->baseUrl()."/section/production/void/id/";?>';
    const confirmed = confirm("តើអ្នកចង់មោឃៈផលិតផលនេះទេ?"); 
    if (confirmed) {
		 if(index!=''){
			window.location.href = url+index;
		}else{
			alert('Please select record you want to void');
			return false;
		}
    }
    return false;
}
</script>
