 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();

	$pageTitle = $tr->translate("CHANGE_PASSWORD");
	$this->headTitle($pageTitle);
	echo $this->headTitle();
	
	$frm = $this->frm;
?>

<div class="container fb">
	<div class="col-12">
		<div class="card">
			<div class="card-header">
				<h5 class="title"><?php echo $pageTitle;?></h5>
			</div>
			<div class="card-body">
				<div class="basic-form">
					<form id="form-submit" method="POST">
						
						<div class="mb-3 input-group">
							<?php echo $frm->getElement('password');?>
							<span class="input-group-text show-pass show-pass-control"> 
								<i class="fa fa-eye-slash"></i>
								<i class="fa fa-eye"></i>
							</span>
						</div>
						<div class="mb-3 input-group">
							<?php echo $frm->getElement('confirmPassword');?>
							<span class="input-group-text show-pass show-pass-control"> 
								<i class="fa fa-eye-slash"></i>
								<i class="fa fa-eye"></i>
							</span>
						</div>
						<button type="submit" class="btn btn-primary mt-3 btn-rounded btn-block"><?php echo $tr->translate('SAVE');?></button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
$( document ).ready(function() {
    $('.classHeadTitle').html("<?php echo $pageTitle;?>");
	$("#form-submit").submit(function() {
		var password = $('#password').val();
		if(password == null || password==""){
			showToastMessage("<?php echo $tr->translate("passwordIsRequired");?>");
			$('#password').focus();
			return false;
		}
		var confirmPassword = $('#confirmPassword').val();
		if(password != confirmPassword ){
			showToastMessage("<?php echo $tr->translate("passwordAndConfirmPasswordNotMatch");?>");
			$('#password').focus();
			return false;
		}
		loading();
		return true;
	});
});
</script>