 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();

	$pageTitle = $tr->translate("CREATE_USER_TYPE");
	$this->headTitle($pageTitle);
	echo $this->headTitle();
	
	$frm = $this->frm;
?>

<div class="container fb">
	<div class="col-12">
		<div class="card">
			<div class="card-header">
				<h5 class="title"><?php echo $pageTitle;?></h5>
			</div>
			<div class="card-body">
				<div class="basic-form">
					<form id="form-submit" method="POST">
						<div class="mb-3 form-input">
							<span class="input-icon">
							   <i class="fa fa-id-card"></i>
							</span>
							<?php echo $frm->getElement('parent');?>
						</div>
						<div class="mb-3 form-input">
							<span class="input-icon">
							   <i class="fa fa-signature"></i>
							</span>
							<?php echo $frm->getElement('title');?>
							
						</div>
						<button type="submit" class="btn btn-primary mt-3 btn-rounded btn-block"><?php echo $tr->translate('SAVE');?></button>
					</form>
				</div>
			</div>
		</div>
	</div>  
</div>
<script>

$( document ).ready(function() {
    $('.classHeadTitle').html("<?php echo $pageTitle;?>");
	$("#form-submit").submit(function() {
		var title = $('#title').val();
		if(title == null || title==""){
			showToastMessage("<?php echo $tr->translate("titleIsRequired");?>");
			$('#title').focus();
			return false;
		}
		
		loading();
		return true;
	});
});
</script>