 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$pageTitle = $tr->translate("EDIT_REVENUE");
	
	$this->headTitle($pageTitle);
	echo $this->headTitle();
	
	$frm = $this->frm;
	$statusLable = $tr->translate("DEACTIVE");
	if($this->row["status"]==1){
		$statusLable = $tr->translate("ACTIVE");
	}
?>
	<div class="container fb">
		<div class="col-12">
			<form id="form-submit" method="POST">
				<div class="card">
					<div class="card-header">
						<h5 class="title"><?php echo $pageTitle;?></h5>
						<div class="form-check form-switch">
						  <input onChange="statusLabel();" class="form-check-input form-check-success" id="status" name="status" type="checkbox" <?php if($this->row["status"]==1){ echo "checked"; } ?> >
						  <label class="form-check-label form-label-status" for="status"><?php echo $statusLable;?></label>
						</div>
					</div>
					<div class="card-body">
						<div class="basic-form">
							<div class="mb-3 form-input">
								<span class="input-icon">
								   <i class="fa fa-calendar-days"></i>
								</span>
								<?php echo $frm->getElement('forDate');?>
								<?php echo $frm->getElement('id');?>
							</div>
							<div class="mb-3 form-input">
								<?php echo $frm->getElement('categoryId');?>
							</div>
							<div class="mb-3 form-input">
								<span class="input-icon">
								   <i class="fa fa-newspaper"></i>
								</span>
								<?php echo $frm->getElement('revenueTitle');?>
							</div>
							<div class="mb-3 form-input">
								<span class="input-icon">
									<i class="fa fa-dollar-sign"></i>
								</span>
								<?php echo $frm->getElement('totalAmount');?>
							</div>
							<div class="mb-3 form-input">
								<?php echo $frm->getElement('bankId');?>
							</div>
							<div class="mb-3">
								<?php echo $frm->getElement('note');?>
							</div>
							<button type="submit" class="btn btn-primary mt-3 btn-rounded btn-block"><?php echo $tr->translate('SAVE');?></button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>

<script>
$( document ).ready(function() {
	
    $('.classHeadTitle').html("<?php echo $pageTitle;?>");
	
	$("#form-submit").submit(function() {
		var categoryId = $('#categoryId').val();
		if(categoryId == null || categoryId==0){
			showToastMessage("<?php echo $tr->translate("categoryIsRequired");?>");
			$('#categoryId').focus();
			return false;
		}
		var bankId = $('#bankId').val();
		if(bankId == null || bankId==0){
			showToastMessage("<?php echo $tr->translate("bankIsRequired");?>");
			$('#bankId').focus();
			return false;
		}
		var totalAmount = $('#totalAmount').val();
		totalAmount = isNaN(totalAmount) ? 0 : totalAmount;
		
		if(totalAmount <=0 ){
			showToastMessage("<?php echo $tr->translate("invalidTotalAmount");?>");
			$('#totalAmount').focus();
			return false;
		}
		loading();
		return true;
	});
});

function statusLabel(){
	if ($('#status').is(':checked')) {
		$('.form-label-status').html("<?php echo $tr->translate("ACTIVE");?>");
	}else{
		$('.form-label-status').html("<?php echo $tr->translate("DEACTIVE");?>");
	}
}
</script>