<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	
	$key = new Application_Model_DbTable_DbKeycode();
	$dataInfo=$key->getKeyCodeMiniInv(TRUE);
	
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$currentLang = $dbGb->currentlang();
	
	
	$clientTitle= "BK Operation App";
	
	$defaultLogo = $this->baseUrl()."/images/Logo.png";
	
	$allLanguage = array();
	$userID = 0;
	$userName = "";
	$isHomeDash = 0;
	$homeTransparent = "bg-primary";
	if($module!="default"){
		$allLanguage = $dbGb->getAllLaguage();
		$zendRequest = new Zend_Controller_Request_Http();
		$userID = $zendRequest->getCookie(SYSTEM_SES.'userID');
		$userID = empty($userID) ? 0 : $userID;
		$userName = $zendRequest->getCookie(SYSTEM_SES.'userName');
		
		$dbGb = new Application_Model_DbTable_DbUsers();
		$userInfo = $dbGb->getUserInformationById($userID);
		
		if(!empty($userInfo)){
			$lastName = empty($userInfo["last_name"]) ? "" : " ".$userInfo["last_name"];
			$firstName = empty($userInfo["first_name"]) ? "" : $userInfo["first_name"];
			
			$userName = $firstName.$lastName;
		}
		
    	if (empty($userID)){
    		Application_Form_FrmMessage::redirectUrl("/");
    	}
		
		if($module=="home" AND $controller=="index" AND $action=="index"){
			$isHomeDash=1;
			$homeTransparent = "transparent";
		}
	}
	
	$langButtonStr="";
	$currentLangStr="";
	
	if(!empty($allLanguage)) foreach($allLanguage as $lang){
		$spanCheck="";
		if($currentLang==$lang["id"]){
			$currentLangStr='<img src="'.$baseUrl."images/".$lang["iconImage"].'" class="media-30 rounded-circle" alt="language-image">';
			$spanCheck='<i class="text-success fa fa-circle-check"></i>';
			
		}
		$langButtonStr.='
				<a onclick="changeLange('.$lang['id'].');" class="btn btn-light w-100 mb-1 d-flex justify-content-between" href="javascript:void(0);" >
				   <div>
						<img src="'.$baseUrl."images/".$lang["iconImage"].'" class="media-30 rounded-circle" alt="language-image"> <span class="ms-2">'.$lang["title"].'</span>
					</div>
					'.$spanCheck.'
				</a>
			';
	}
	
 ?>
<!DOCTYPE html>
<html lang="en">
<head>
    
    <!-- Meta -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, minimal-ui, viewport-fit=cover">
	<meta name="theme-color" content="#001ba9">
	<!-- Title -->
	<meta content="<?php echo $clientTitle; ?>" name="author" />
    <meta name="keywords" content="" /> 
    <meta name="robots" content="" /> 
	<meta content="<?php echo $clientTitle; ?> Mobile App" name="description" />
	<meta property="og:title" content="<?php echo $clientTitle; ?> Mobile App" />
	<meta property="og:description" content="<?php echo $clientTitle; ?> Mobile App" />
	<meta property="og:image" content="<?php echo $baseUrl."images/"; ?>/icon.ico"/>
	<meta name="format-detection" content="telephone=no">
   
	
	<!-- PWA Version -->
	<link rel="manifest" href="<?php echo $baseUrl."templates/"; ?>manifest.json">
	
    <!-- Favicons Icon -->
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo $baseUrl."images/"; ?>/icon.ico" />
    
    <!-- Stylesheets -->
    <link rel="stylesheet" href="<?php echo $baseUrl."templates/"; ?>assets/vendor/swiper/swiper-bundle.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl."templates/"; ?>assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl."templates/"; ?>assets/css/materialize.min.css">
    
    <script src="<?php echo $baseUrl."templates/"; ?>assets/js/jquery.js"></script>
</head>   
<body class="bg-white">
<div class="page-wraper">
	<!-- Preloader -->
	<div id="preloader">
		<div class="spinner"></div>
	</div>
    <!-- Preloader end-->
	<div class="loading-screen">
		<div class="spinner"></div>
	</div>
	<?php if($module!="default"){ ?>
	<!-- Header -->
	<header class="header <?php echo $homeTransparent;?>">
		<div class="main-bar">
			<div class="container">
				<?php if($isHomeDash==1){?>
				<div class="header-content">
					<div class="left-content">
						<a href="javascript:void(0);" class="menu-toggler">
							<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path opacity="0.4" d="M16.0755 2H19.4615C20.8637 2 22 3.14585 22 4.55996V7.97452C22 9.38864 20.8637 10.5345 19.4615 10.5345H16.0755C14.6732 10.5345 13.537 9.38864 13.537 7.97452V4.55996C13.537 3.14585 14.6732 2 16.0755 2Z" fill="#a19fa8"/>
								<path fill-rule="evenodd" clip-rule="evenodd" d="M4.53852 2H7.92449C9.32676 2 10.463 3.14585 10.463 4.55996V7.97452C10.463 9.38864 9.32676 10.5345 7.92449 10.5345H4.53852C3.13626 10.5345 2 9.38864 2 7.97452V4.55996C2 3.14585 3.13626 2 4.53852 2ZM4.53852 13.4655H7.92449C9.32676 13.4655 10.463 14.6114 10.463 16.0255V19.44C10.463 20.8532 9.32676 22 7.92449 22H4.53852C3.13626 22 2 20.8532 2 19.44V16.0255C2 14.6114 3.13626 13.4655 4.53852 13.4655ZM19.4615 13.4655H16.0755C14.6732 13.4655 13.537 14.6114 13.537 16.0255V19.44C13.537 20.8532 14.6732 22 16.0755 22H19.4615C20.8637 22 22 20.8532 22 19.44V16.0255C22 14.6114 20.8637 13.4655 19.4615 13.4655Z" fill="#a19fa8"/>
							</svg>
						</a>
					</div>
					<div class="mid-content">
						<h5 class="mb-0 classHeadTitle"></h5>
					</div>
					<div class="right-content">
						<a href="javascript:void(0);" data-bs-toggle="offcanvas" data-bs-target="#offcanvasLanguage" aria-controls="offcanvasBottom">
                            <?php echo $currentLangStr;?>
                        </a>
                        <a href="javascript:void(0);" class="theme-btn">
                            <svg class="dark" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"   stroke-linecap="round" stroke-linejoin="round">
                                <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
                            </svg> 
							<svg class="light" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"></circle><line x1="12" y1="1" x2="12" y2="3"></line><line x1="12" y1="21" x2="12" y2="23"></line><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line><line x1="1" y1="12" x2="3" y2="12"></line><line x1="21" y1="12" x2="23" y2="12"></line><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line></svg>
                        </a>
					</div>
				</div>
				<?php }else {?>
				<div class="header-content">
                    <div class="left-content">
                        <a href="javascript:void(0);" class="back-btn">
                            <svg width="18" height="18" viewBox="0 0 10 16" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M9.03033 0.46967C9.2966 0.735936 9.3208 1.1526 9.10295 1.44621L9.03033 1.53033L2.561 8L9.03033 14.4697C9.2966 14.7359 9.3208 15.1526 9.10295 15.4462L9.03033 15.5303C8.76406 15.7966 8.3474 15.8208 8.05379 15.6029L7.96967 15.5303L0.96967 8.53033C0.703403 8.26406 0.679197 7.8474 0.897052 7.55379L0.96967 7.46967L7.96967 0.46967C8.26256 0.176777 8.73744 0.176777 9.03033 0.46967Z" fill="#a19fa8"/>
							</svg>
                        </a>
                    </div>
                    <div class="mid-content">
                        <h5 class="mb-0 classHeadTitle"></h5>
                    </div>
                    <div class="right-content">
					
                        <a href="javascript:void(0);" class="menu-toggler">
							<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path opacity="0.4" d="M16.0755 2H19.4615C20.8637 2 22 3.14585 22 4.55996V7.97452C22 9.38864 20.8637 10.5345 19.4615 10.5345H16.0755C14.6732 10.5345 13.537 9.38864 13.537 7.97452V4.55996C13.537 3.14585 14.6732 2 16.0755 2Z" fill="#a19fa8"/>
								<path fill-rule="evenodd" clip-rule="evenodd" d="M4.53852 2H7.92449C9.32676 2 10.463 3.14585 10.463 4.55996V7.97452C10.463 9.38864 9.32676 10.5345 7.92449 10.5345H4.53852C3.13626 10.5345 2 9.38864 2 7.97452V4.55996C2 3.14585 3.13626 2 4.53852 2ZM4.53852 13.4655H7.92449C9.32676 13.4655 10.463 14.6114 10.463 16.0255V19.44C10.463 20.8532 9.32676 22 7.92449 22H4.53852C3.13626 22 2 20.8532 2 19.44V16.0255C2 14.6114 3.13626 13.4655 4.53852 13.4655ZM19.4615 13.4655H16.0755C14.6732 13.4655 13.537 14.6114 13.537 16.0255V19.44C13.537 20.8532 14.6732 22 16.0755 22H19.4615C20.8637 22 22 20.8532 22 19.44V16.0255C22 14.6114 20.8637 13.4655 19.4615 13.4655Z" fill="#a19fa8"/>
							</svg>
						</a>
                    </div>
                </div>
				<?php }?>
			</div>
		</div>
	</header>
    <!-- Header End -->
	<?php 
		echo $this->render('navigation.phtml');
	 ?>
   
	<?php if($module=="home" AND $controller=="index" AND $action=="index"){?>
		<!-- Banner -->
		<div class="banner-wrapper author-notification">
			<div class="container inner-wrapper">
				<div class="dz-info">
					<span><?php echo $tr->translate("WELCOME"); ?></span>
					<h2 class="name mb-0"><?php echo $userName; ?></h2>
				</div>
				<div class="dz-media media-45 rounded-circle">
					<a href="javascript:void(0);"><img src="<?php echo $baseUrl."images/"; ?>/user.png" class="rounded-circle" alt="author-image"></a>
				</div>
			</div>
		</div>
		<!-- Banner End -->
		<?php  } ?>
	<?php  } ?>
	
    <!-- Page Content -->
    <div class="page-content">
        
        <?php
			//echo $this->layout()->content;

			if($module=="default" AND $controller=='index' AND $action=='index'){
				echo $this->layout()->content;
			}else{
				$db_user = new Application_Model_DbTable_DbUsers();
				$rs = $db_user->getAccessUrl($module,$controller,$action);
				echo $this->layout()->content;
				if(!empty($rs) OR $action=='changepassword' ){
					//echo $this->layout()->content;
				}else{
					//echo $this->render('pagenotfund.phtml');
				}
				
			}
		?>
    </div>
    <!-- Page Content End -->
	
	<?php if($isHomeDash==1){?>
	<div class="offcanvas offcanvas-bottom" tabindex="-1" id="offcanvasLanguage">
        <div class="offcanvas-body small">
            <div class="modal-header">
				<h5 class="modal-title"><?php echo $tr->translate("LANGUAGE");?></h5>
				<button class="btn-close" data-bs-dismiss="offcanvas">
					<i class="fa-solid fa-xmark"></i>
				</button>
			</div>
			<div class="modal-body">
				<?php echo $langButtonStr;?>
			</div>
        </div>
    </div>
	<?php } ?>
	
	
	<?php if($module!="default"){ ?>
		<?php if ($module != 'home' and $module != 'default' and ( $action == "index") and ( $controller !='report') ) { ?>
			
			<a class="p-2  btn btn-primary rounded-circle btn-rounded create-btn"  href="<?php echo $this->url(array('module' => $module, 'controller' => $controller, 'action' => 'add'), null, true); ?>" >
				<i class="fa-solid fa-plus"></i>
			</a>
		<?php } ?>
		
		
	<?php } ?>
</div>


<div id="toastMessage" class="bottom-right dzToastArea toast style-1 toast-danger dz-toast on-bottom fade hide" role="alert" aria-live="polite" aria-atomic="true">
	<div class="toast-body">
		<i class="fa fa-circle-info"></i>
		<div class="toast-content ms-3 me-2">
		</div>
		<button class="btn btn-close position-absolute p-1" type="button" data-bs-dismiss="toast" aria-label="Close"> </button>                        
	</div>
</div>
<script type="text/javascript">

function changeLange(lang){
	loading();
	var urlChangelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
	jQuery.ajax({
		url: urlChangelang,
		type: "post",
		data:{'lange':lang},
		success: function(data){
			location.reload();
		},
		error:function(err){
			
		}
	});
}
</script>					
<!--**********************************
    Scripts
***********************************-->
<?php if($isHomeDash==1 || $module=="default"){?>
<!--<script src="<?php //echo $baseUrl."templates/"; ?>js/index.js"></script>-->
<?php } ?>

<script src="<?php echo $baseUrl."templates/"; ?>assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<script src="<?php echo $baseUrl."templates/"; ?>assets/js/dz.carousel.js"></script><!-- Swiper -->
<script src="<?php echo $baseUrl."templates/"; ?>assets/vendor/swiper/swiper-bundle.min.js"></script><!-- Swiper -->

<script src="<?php echo $baseUrl."templates/"; ?>assets/js/materialize.js"></script>
<script src="<?php echo $baseUrl."templates/"; ?>assets/js/settings.js"></script>
<script src="<?php echo $baseUrl."templates/"; ?>assets/js/custom.js"></script>
</body>
</html>