 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$pageTitle = "កែប្រែអតិថិជន";
	
	$this->headTitle($pageTitle);
	echo $this->headTitle();
	
?>
	<div class="container fb">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
					<h5 class="title"><?php echo $pageTitle;?></h5>
				</div>
				<div class="card-body">
					<div class="basic-form">
						<form id="form-submit" action="" method="POST" >
							<div class="mb-3 form-input">
								<span class="input-icon">
								   <i class="fa fa-user"></i>
								</span>
								<input type="text" name="customerName" id="customerName" value="<?php echo $this->rs['customerName'];?>" class="form-control" placeholder="ឈ្មោះអតិថិជន" required="required" autocomplete="off">	
								<input type="hidden" name="customerId" id="customerId" value="<?php echo $this->rs['id'];?>" class="form-control" placeholder="customerId">	
							</div>
							<div class="mb-3 form-input">
								<span class="input-icon">
									<i class="fa-solid fa-address-book"></i>
								</span>
								<input type="text" name="contactName" id="contactName" value="<?php echo $this->rs['contactName'];?>" class="form-control" placeholder="ឈ្មោះសម្រាប់ទំនាក់ទំនង" required="required" autocomplete="off">
							</div>
							<div class="mb-3 form-input">
								<span class="input-icon">
								   <i class="fa-solid fa-phone"></i>
								</span>
								<input type="text" name="contactTel" id="contactTel" value="<?php echo $this->rs['contactTel'];?>" class="form-control" placeholder="ទូរស័ព្ទ" required="required" autocomplete="off">
							</div>
							<div class="mb-3 form-input">
								<span class="input-icon">
								   <i class="fa-solid fa-map"></i>
								</span>
								<input type="text" name="address" id="address" value="<?php echo $this->rs['address'];?>"" class="form-control" placeholder="អាសយដ្ឋាន" autocomplete="off">
							</div>
							<div class="form-check form-switch">
								<label class="form-check-label" for="status"><?php echo $tr->translate('STATUS');?></label>
								<input class="form-check-input form-check-info" id="status" name="status" type="checkbox" <?php if($this->rs['status']==1){ echo "checked"; } ?>  > 
							</div>
							<button type="submit" class="btn btn-primary mt-3 btn-rounded btn-block"><?php echo $tr->translate('SAVE');?></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

<script>
$( document ).ready(function() {
    $('.classHeadTitle').html("<?php echo $pageTitle;?>");
	
	$("#form-submit").submit(function() {
	  return true;
	});
});
</script>