<?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$pageTitle = $tr->translate("EDIT_BANK");
	$this->headTitle($pageTitle);
	echo $this->headTitle();
	$frm = $this->frm;
	
?>
	<div class="container fb">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
					<h5 class="title"><?php echo $pageTitle;?></h5>
				</div>
				<div class="card-body">
					<div class="basic-form">
						<form id="form-submit" action="<?php echo $this->url(array('module'=>'section','controller'=>'bank','action'=>'edit')); ?>" method="POST" >
							<div class="mb-3 form-input">
								<span class="input-icon">
									<i class="fa-solid fa-building-columns"></i>
								</span>
								<?php echo $frm->getElement('bankName');?>
								<?php echo $frm->getElement('id');?>
							</div>
							<div class="mb-3 form-input">
								<span class="input-icon">
									<i class="fa-solid fa-address-book"></i>
								</span>
								<?php echo $frm->getElement('accountName');?>
							</div>
							<div class="mb-3 form-input">
								<span class="input-icon">
									<i class="fa-solid fa-money-check-dollar"></i>
								</span>
								<?php echo $frm->getElement('accountNumber');?>
							</div>
							<div class="mb-3 form-input">
								<span class="input-icon">
									<i class="fa-solid fa-hand-holding-dollar"></i>
								</span>
								<?php echo $frm->getElement('totalBalance');?>
							</div>
							<button type="submit" class="btn btn-primary mt-3 btn-rounded btn-block"><?php echo $tr->translate('SAVE');?></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

<script>
$( document ).ready(function() {
    $('.classHeadTitle').html("<?php echo $pageTitle;?>");
	
	$("#form-submit").submit(function() {
	  return true;
	});
});
</script>