 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$pageTitle = $tr->translate("BANK");
	$this->headTitle($pageTitle);
	echo $this->headTitle();
	
	$frm = $this->frm;
	$urlEdit = $this->baseUrl()."/section/bank/edit/id/";
	$addUrl = $this->baseUrl()."/section/bank/add";
?>
	<div class="page-content">
		<div class="container"> 
			<div class="serach-area"> 
				<form id="form-submit" action="<?php echo $this->url(array('module'=>'section','controller'=>'bank','action'=>'index')); ?>" method="POST" >
					<div class="input-group search-input">
						<?php echo $frm->getElement('search');?>
					</div>
					<div class="filter-area">
						<div>
							<h5><?php echo $pageTitle; ?></h5>
							<span><?php echo count($this->rs); ?> Bank Accounts</span>
						</div>
						<button type="submit" class="btn  filter-btn bg-skyblue light"><i class="fa-solid fa-magnifying-glass"></i></button>
					</div>
				</form>
				<?php if(!empty($this->rs)){?>
				<div class="dz-list data-list">
					<ul>
						<?php $i=0; 
						foreach($this->rs AS $rs){ $i++;
							
						
						?>
						<li>
							<div  class="item-content item-link">
								<div class="dz-icon bg-primary light">
									<?php echo $i;?>                                  
								</div>
								<div class="dz-inner d-flex align-items-center w-100">
									<div class="dz-title flex-1">
										<span class="dz-title"><?php echo $rs["bankName"];?></span>
										<span class="text-muted d-block fw-normal"><i class="fa-solid fa-address-book me-2"></i><?php echo $rs['accountName']; ?></span>
										<span class="text-muted d-block fw-normal"><i class="fa-solid fa-money-check-dollar me-2"></i><?php echo $rs['accountNumber']; ?></span>
										<span class="text-red d-block fw-bold"><i class="fa-solid fa-hand-holding-dollar me-2"></i><?php echo $rs['totalBalance']; ?></span>
									</div>
									<a class="btn light btn-warning fs-6 p-2 ms-2 fw-normal" href="<?php echo $urlEdit.$rs["id"]; ?>" >
									<i class="fa fa-edit"></i>
									</a>
								</div>
							</div>
						</li>
						<?php } ?>
					</ul>        
				</div>   
				<?php } ?>  
				
				                
			</div>    
		</div>
	</div>
<script>

$( document ).ready(function() {
    $('.classHeadTitle').html("<?php echo $pageTitle;?>");
});
</script>
